### ISSUE TITLE
Support for a configuration file

### ISSUE THREAD

**Issue by oleiade** [oleiade/trousseau#105]
It has been a long running request. Now, it is time. Trousseau should support the usage of an optional configuration file in `$HOME/.trousseau` directory.

Proposed format uses yaml and goes like this:

``` yaml
encryption:
  openpgp:
    gnupg_home: '~/.gnupg'

authentication:
  keyring:
    entry: 'trousseau_passphrase'
  gpg_agent:
    info_file: '/tmp/myinfo_file'
    master_key: '12983AB4E'

remote_storages:
  mys3: s3://aws_access_key:aws_secret_key@bucket:region/remote_file_path
  myothers3: s3://aws_access_key:aws_secret_key@bucket:region/remote_file_path
  gist: gist://user:mysupperduppertoken@:/gist_name
  ssh: scp://user:@host:port/remote_file_path
```

Proposed according behavior changes are:
- trousseau push/pull should support whether `trousseau push remote_storage_name` and `trousseau push myendpointdsn` #106 
- trousseau should support both environment and configuration file variables. Environment priority is higher than configuration file and the former will always overrider the later.
- trousseau should expose a configure command to interactively produce a configuration file #107
- trousseau configuration file must be optional

Further enhancements:
- Reference stores in configuration file

Depends on #103
